export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST"
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS"
export const USER_LOGIN_FAILURE = "USER_LOGIN_FAILURE"
export const USER_ADD_REQUEST = "USER_ADD_REQUEST"
export const USER_ADD_SUCCESS = "USER_ADD_SUCCESS"
export const USER_ADD_FAILURE = "USER_ADD_FAILURE"

